C     Last change: KU 19.04.2021 18:13:12
C
C     2. Ableitungen Y2EXP aus X und Y berechnen
C
      SUBROUTINE SPLINDLL(N,X,Y,Y2EXP,XSI,YP1,YPN)
      IMPLICIT REAL(KIND=8) (A-H,O-Z)
      REAL(KIND=8),DIMENSION(*) :: X,Y,Y2EXP
      REAL(KIND=8) :: XSI,YP1,YPN
C
C
C
      DLL_EXPORT SPLINDLL
C
C
C
C
      CALL SPLINEX(N,X,Y,Y2EXP,XSI,YP1,YPN)
      RETURN
      END SUBROUTINE
C
C     YS(Wert) YSDX(zugehörige Ableitung) für XS berechnen
C
      SUBROUTINE SPLITDLL(N,X,Y,Y2EXP,XS,YS,XSI,YSDX)
      IMPLICIT REAL(KIND=8) (A-H,O-Z)
      REAL(KIND=8),DIMENSION(*) :: X,Y,Y2EXP
      REAL(KIND=8) :: XSI,XS,YS,YSDX
C
C
C
      INTERFACE
      SUBROUTINE SPLINTX(N,X,Y,Y2EXP,XS,YS,XSI,YSDX)
      INTEGER(KIND=4) ::N
      REAL(KIND=8),DIMENSION(*) :: X,Y,Y2EXP
      REAL(KIND=8) :: XS,YS,XSI
      REAL(KIND=8),OPTIONAL  ::YSDX
      END SUBROUTINE
      END INTERFACE
C
C
C
      DLL_EXPORT SPLITDLL
C
C
C
C
      CALL SPLINTX(N,X,Y,Y2EXP,XS,YS,XSI,YSDX)

      RETURN
      END SUBROUTINE
c
c
c
c
c
c

